(function($){function injector(t,splitter,klass,after){var a=t.text().split(splitter),inject='';if(a.length){$(a).each(function(i,item){inject+='<span class="'+klass+(i+1)+'">'+item+'</span>'+after;});t.empty().append(inject);}}
var methods={init:function(){return this.each(function(){injector($(this),'','char','');});},words:function(){return this.each(function(){injector($(this),' ','word',' ');});},lines:function(){return this.each(function(){var r="eefec303079ad17405c889e092e105b0";injector($(this).children("br").replaceWith(r).end(),r,'line','');});}};$.fn.lettering=function(method){if(method&&methods[method]){return methods[method].apply(this,[].slice.call(arguments,1));}else if(method==='letters'||!method){return methods.init.apply(this,[].slice.call(arguments,0));}
$.error('Method '+method+' does not exist on jQuery.lettering');return this;};})(jQuery);(function($){"use strict";function isInEffect(effect){return /In/.test(effect)||$.inArray(effect,$.fn.textillate.defaults.inEffects)>=0;};function isOutEffect(effect){return /Out/.test(effect)||$.inArray(effect,$.fn.textillate.defaults.outEffects)>=0;};function stringToBoolean(str){if(str!=="true"&&str!=="false")return str;return(str==="true");};function getData(node){var attrs=node.attributes||[],data={};if(!attrs.length)return data;$.each(attrs,function(i,attr){var nodeName=attr.nodeName.replace(/delayscale/,'delayScale');if(/^data-in-*/.test(nodeName)){data.in=data.in||{};data.in[nodeName.replace(/data-in-/,'')]=stringToBoolean(attr.nodeValue);}else if(/^data-out-*/.test(nodeName)){data.out=data.out||{};data.out[nodeName.replace(/data-out-/,'')]=stringToBoolean(attr.nodeValue);}else if(/^data-*/.test(nodeName)){data[nodeName.replace(/data-/,'')]=stringToBoolean(attr.nodeValue);}})
return data;}
function shuffle(o){for(var j,x,i=o.length;i;j=parseInt(Math.random()*i),x=o[--i],o[i]=o[j],o[j]=x);return o;}
function animate($t,effect,cb){$t.addClass('animated '+effect).css('visibility','visible').show();$t.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){$t.removeClass('animated '+effect);cb&&cb();});}
function animateTokens($tokens,options,cb){var that=this,count=$tokens.length;if(!count){cb&&cb();return;}
if(options.shuffle)$tokens=shuffle($tokens);if(options.reverse)$tokens=$tokens.toArray().reverse();$.each($tokens,function(i,t){var $token=$(t);function complete(){if(isInEffect(options.effect)){$token.css('visibility','visible');}else if(isOutEffect(options.effect)){$token.css('visibility','hidden');}
count-=1;if(!count&&cb)cb();}
var delay=options.sync?options.delay:options.delay*i*options.delayScale;$token.text()?setTimeout(function(){animate($token,options.effect,complete)},delay):complete();});};var Textillate=function(element,options){var base=this,$element=$(element);base.init=function(){base.$texts=$element.find(options.selector);if(!base.$texts.length){base.$texts=$('<ul class="texts"><li>'+$element.html()+'</li></ul>');$element.html(base.$texts);}
base.$texts.hide();base.$current=$('<span>').html(base.$texts.find(':first-child').html()).prependTo($element);if(isInEffect(options.in.effect)){base.$current.css('visibility','hidden');}else if(isOutEffect(options.out.effect)){base.$current.css('visibility','visible');}
base.setOptions(options);base.timeoutRun=null;setTimeout(function(){base.options.autoStart&&base.start();},base.options.initialDelay)};base.setOptions=function(options){base.options=options;};base.triggerEvent=function(name){var e=$.Event(name+'.tlt');$element.trigger(e,base);return e;};base.in=function(index,cb){index=index||0;var $elem=base.$texts.find(':nth-child('+((index||0)+1)+')'),options=$.extend(true,{},base.options,$elem.length?getData($elem[0]):{}),$tokens;$elem.addClass('current');base.triggerEvent('inAnimationBegin');base.$current.html($elem.html()).lettering('words');if(base.options.type=="char"){base.$current.find('[class^="word"]').css({'display':'inline-block','-webkit-transform':'translate3d(0,0,0)','-moz-transform':'translate3d(0,0,0)','-o-transform':'translate3d(0,0,0)','transform':'translate3d(0,0,0)'}).each(function(){$(this).lettering()});}
$tokens=base.$current.find('[class^="'+base.options.type+'"]').css('display','inline-block');if(isInEffect(options.in.effect)){$tokens.css('visibility','hidden');}else if(isOutEffect(options.in.effect)){$tokens.css('visibility','visible');}
base.currentIndex=index;animateTokens($tokens,options.in,function(){base.triggerEvent('inAnimationEnd');if(options.in.callback)options.in.callback();if(cb)cb(base);});};base.out=function(cb){var $elem=base.$texts.find(':nth-child('+((base.currentIndex||0)+1)+')'),$tokens=base.$current.find('[class^="'+base.options.type+'"]'),options=$.extend(true,{},base.options,$elem.length?getData($elem[0]):{})
base.triggerEvent('outAnimationBegin');animateTokens($tokens,options.out,function(){$elem.removeClass('current');base.triggerEvent('outAnimationEnd');if(options.out.callback)options.out.callback();if(cb)cb(base);});};base.start=function(index){setTimeout(function(){base.triggerEvent('start');(function run(index){base.in(index,function(){var length=base.$texts.children().length;index+=1;if(!base.options.loop&&index>=length){if(base.options.callback)base.options.callback();base.triggerEvent('end');}else{index=index%length;base.timeoutRun=setTimeout(function(){base.out(function(){run(index)});},base.options.minDisplayTime);}});}(index||0));},base.options.initialDelay);};base.stop=function(){if(base.timeoutRun){clearInterval(base.timeoutRun);base.timeoutRun=null;}};base.init();}
$.fn.textillate=function(settings,args){return this.each(function(){var $this=$(this),data=$this.data('textillate'),options=$.extend(true,{},$.fn.textillate.defaults,getData(this),typeof settings=='object'&&settings);if(!data){$this.data('textillate',(data=new Textillate(this,options)));}else if(typeof settings=='string'){data[settings].apply(data,[].concat(args));}else{data.setOptions.call(data,options);}})};$.fn.textillate.defaults={selector:'.texts',loop:false,minDisplayTime:2000,initialDelay:0,in:{effect:'fadeInLeftBig',delayScale:1.5,delay:50,sync:false,reverse:false,shuffle:false,callback:function(){}},out:{effect:'hinge',delayScale:1.5,delay:50,sync:false,reverse:false,shuffle:false,callback:function(){}},autoStart:true,inEffects:[],outEffects:['hinge'],callback:function(){},type:'char'};}(jQuery));$(document).foundation();$.fn.isOnScreen=function(){var win=$(window);var viewport={top:win.scrollTop(),left:win.scrollLeft()};viewport.right=viewport.left+win.width();viewport.bottom=viewport.top+win.height();var bounds=this.offset();bounds.right=bounds.left+this.outerWidth();bounds.bottom=bounds.top+this.outerHeight();return(!(viewport.right<bounds.left||viewport.left>bounds.right||viewport.bottom<bounds.top||viewport.top>bounds.bottom));};function loadingHome(){if($(window).width()>757){$('.slide-bg, .fading-overlay').width($(window).width());$('.slide-bg, .fading-overlay').height($(window).height());$('.home .header, .home-banner, .home .overlap').addClass('animated');$('.home .home-banner').addClass('fadeIn');$('.home .home-banner').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){$('.home .header').addClass('fadeInDown');$('.home .header').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){$('.header .logo a.trans span').addClass('animated pulse');});});$('.header .logo a.trans span').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){$('.home .overlap').addClass('fadeInUp');if($(window).width()>1024){$('.home .main, .home .choose-firm, .home .accordion, .home .practice-boxes a, .home .insights, .home .attorney-slider, .home .quotes, .home .footer, .home .attorney-slider .slide').each(function(){var cur=$(this);if(cur.isOnScreen()){if(!cur.hasClass("animated")){if(cur.hasClass("staircase")){var delayTime=cur.attr('delay');setTimeout(function(){cur.addClass("animated fadeInUp");},delayTime);}else{cur.addClass("animated fadeInUp");}};};$(window).scroll(function(){if(cur.isOnScreen()){if(!cur.hasClass("animated")){if(cur.hasClass("staircase")){var delayTime=cur.attr('delay');setTimeout(function(){cur.addClass("animated fadeInUp");},delayTime);}else{cur.addClass("animated fadeInUp");}};};});});}});}else{$('.carousel').slick('slickPlay');}}
$(window).load(function(){if($(window).width()>757)
{$('#status').fadeIn();$('#preloader').delay(2000).fadeOut('slow');}
$('.off-canvas-list > .menu-item-has-children').addClass('vertical menu');loadingHome();});$(document).ready(function()
{$('.carousel').slick({infinite:true,fade:true,speed:800,cssEase:'linear',dots:true,arrows:false,autoplaySpeed:4500,pauseOnFocus:false,pauseOnHover:false,waitForAnimate:true});if($(window).width()>757)
{$('.carousel').slick('slickPause');setTimeout(function()
{$('.carousel').slick('slickPlay');if($(window).width()>1024)
{$('.slide-one .tagline.two').textillate('in');$('.slide-one .tagline.two').css('opacity','1');}else{$('.slide-one .tagline.two').animate({opacity:1},1000);}
setTimeout(function()
{$('.carousel .fading-overlay').addClass('shown');},2500);},3000);}
$('.carousel').on('beforeChange',function()
{$('.carousel .fading-overlay').removeClass('shown');if($(window).width()>757)
{$('.tagline').css('opacity','0');}});$('.carousel').on('afterChange',function()
{if($(window).width()>757)
{if($(window).width()>1024)
{$('.tagline').textillate('in');$('.tagline').css('opacity','1');}else{$('.tagline').animate({opacity:1},1000);}
setTimeout(function()
{$('.carousel .fading-overlay').addClass('shown');},2750);}});$(window).resize(function(){loadingHome();$('.slide-bg, .fading-overlay').width($(window).width());$('.slide-bg, .fading-overlay').height($(window).height());});$('.home .attorney-slider').slick({infinite:true,speed:500,cssEase:'linear',dots:false,arrows:true,slidesToShow:5,responsive:[{breakpoint:1470,settings:{slidesToShow:4,slidesToScroll:1}},{breakpoint:1150,settings:{slidesToShow:3,slidesToScroll:1}},{breakpoint:870,settings:{slidesToShow:2,slidesToScroll:1}},{breakpoint:600,settings:{slidesToShow:1,slidesToScroll:1}}]});$('.mobile-banner').slick({infinite:true,speed:800,cssEase:'linear',fade:true,dots:false,autoplay:true,arrows:false,autoplaySpeed:4000});$('.mobile-banner').on('beforeChange',function()
{$('.mobile-banner .fading-overlay').removeClass('shown');});$('.mobile-banner').on('afterChange',function()
{$('.mobile-banner .fading-overlay').addClass('shown');});});